### ISSUE TITLE
CSS screw up on IE9 and IE8

### ISSUE THREAD

**Issue by sekti92** [coliff/bootstrap-ie8#10]
IE9 - Position of div, not center, navigation button gone, carousel button changed, can
t detect col-md-x class (only show 1 column)
![ie9](https://user-images.githubusercontent.com/14885417/32534443-8e1bb83e-c44d-11e7-9e7b-d09828e84ecb.PNG)

IE8 - Position of div, not center, navigation button gone, carousel button change, cant detect js ( jquery 3.2.1, bootstrap 4.js, popper.js)
![ie8](https://user-images.githubusercontent.com/14885417/32534448-95baadc0-c44d-11e7-8a4f-7e7dab19e28c.PNG)

**Comment by coliff** [comment]
For IE8 - you'd need to use jQuery 1.x. JQuery 3.x won't work with IE8 at all. Bootstrap 4 JS and Popper JS both won't work at all with IE8.

For IE9 - carousel is not yet supported since it requires JavaScript and BS4 dropped support for IE9. Not sure about that col-md-x class. Can you provide a link?

**Comment by coliff** [comment]
There have been lots of improvements since your issue was opened. Please retest with latest release.
