### ISSUE TITLE
IE8 support for CSS Media Query

### ISSUE THREAD

**Issue by namiltd** [coliff/bootstrap-ie8#42]
Look at repository tree: https://github.com/namiltd/bootstrap-ie8/tree/respond
Demo at: http://namiltd.github.io/bootstrap-ie8/test.htm
and http://phpsysinfo.sourceforge.net/phpsysinfo-bs4/
Test it on IE8

**Comment by coliff** [comment]
hey there! this is an interesting idea. Overall though, the aim of this project was for people to very quickly and easily add a tiny snippet of code to the page head so that the conditionally loaded CSS would make Bootstrap 4 sites appear a lot less broken. Adding RespondJS complicates things because it doesn't work on CDN-hosted stylesheets.
Furthermore, I think probably around 99% of IE8 users are using a desktop screen with at least 1000 pixels wide, so they don't need it to be responsive.

The JavaScript polyfills for calc, opacity, rgba etc might be good to add so long as they don't impact performance and they work with CDN-hosted stylesheets, but I wanted the JavaScript file to be optional so I think it's best if the CSS rules we added to address those issues to stay.

I was thinking of listing a few suggestions in the README FAQs for JavaScript polyfill scripts for people to choose whether to add them or not based on their particular project.

**Comment by namiltd** [comment]
Now https://github.com/coliff/bootstrap-ie8/pull/55 code is updated for the future version 4.1.2 of bootstrap

**Comment by namiltd** [comment]
https://github.com/namiltd/bootstrap-ie8 repository
