### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by XpandMarketingLLC** [coliff/bootstrap-ie8#7]
I have implemented this on a client website which is under development. However, it doesn't seem to make a difference. The link is http://cosurica.xpandcreative.co.uk/ could you check that I'm doing it right? 

Thanks

**Comment by TeamUpDevelopment** [comment]
It looks ok for me in IE9 and IE10. I didn't test IE8. My guess you could only really expect it to be usable for IE8, but not the same exact experience as modern browsers.  I did notice that the columns are using classes with the "col-xs-#" which the BS 4 Beta no longer has.  Instead of col-xs-12, use col-12 now with BS 4.

**Comment by coliff** [comment]
Agree with everything that @TeamUpDevelopment has said. I tested it in IE8 and it actually works surprisingly well - even the dropdown menu is functional.

One thing which will make it look a little bit nicer (which I intend to do) is to reduce the widths of all the column classes slightly so that multiple columns in a row don't spill over into a new row. This is down to IE8 not supporting the border-box property.

**Comment by XpandMarketingLLC** [comment]
Is it because I'm using parallels to emulate IE 9? It's really broken in IE 9 for me and doesn't even seem to read the IE9 stylesheet. 

Thanks @TeamUpDevelopment  for the heads up re col-xs. I had a feeling I hadn't seen it in the documentation but old habits and all ;)

**Comment by coliff** [comment]
Not sure why Parallels would be causing the issue - I was testing using Oracle VirtualBox VM with the IE9/Windows 7 image from Microsoft
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Closing this issue now, but feel free to post again with any questions/issues.

**Comment by XpandMarketingLLC** [comment]
It's fine thanks. I later went back and checked it and everything was fine except the menu which I fixed with a few extra classes for IE. 

Thanks
