### ISSUE TITLE
When I open demo page on IE8&IE9 - carousel, tooltips and popover doesn't work

### ISSUE THREAD

**Issue by MandaJC** [coliff/bootstrap-ie8#95]
When I open https://coliff.github.io/bootstrap-ie8/test.htm on IE8&IE9, it doesn't work.
For example:Carousel, Popovers, Tooltips
IE8：
![image](https://user-images.githubusercontent.com/37771526/101858297-48622900-3ba4-11eb-8d30-5e0362b44d49.png)
![image](https://user-images.githubusercontent.com/37771526/101858338-6039ad00-3ba4-11eb-86ac-600660d6dc6d.png)

IE9：
![image](https://user-images.githubusercontent.com/37771526/101858273-37b1b300-3ba4-11eb-9541-957bb9805a0e.png)
![image](https://user-images.githubusercontent.com/37771526/101858360-692a7e80-3ba4-11eb-9373-d73bfcced84a.png)

So how can I use this plugins?

**Comment by KiddoV** [comment]
Same thing, nothing is working.

**Comment by coliff** [comment]
Heya. sorry for the delayed reply! The JS/CSS not loading issue has since been fixed (changed to https://cdn.jsdelivr.net).

The JavaScript errors for the carousel, popover and tooltip could potentially be fixed with something like the Polyfill service: https://polyfill.io/v3/url-builder/ - though I haven't tested it yet. Will leave this issue open in case anyone wants to open a PR with a fix.
